version: 2

# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: monthly
      open-pull-requests-limit: 99
      labels:
          - 'A-dependency/gardening'
          - I-enhancement

    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
      open-pull-requests-limit: 99
      labels:
          - 'A-dependency/gardening'
          - I-enhancement
      ignore:
          # When we upgrade TypeScript, the emitted d.ts code may contain some breaking changes.
          # This mean that we should release its change as major update strictly.
          # Our (current) design allows that an user project contains multiple version of this
          # So we cap to update typescript by dependabot.
          # This does not mean to restrict us. We can update typescript when we want!
          # This make to stop the automatic flow for it.
          - dependency-name: typescript
            update-types: ['version-update:semver-major', 'version-update:semver-minor']
          # FIXME: https://github.com/Nikkei/node-http-helper/issues/300
          - dependency-name: eslint
            update-types: ['version-update:semver-major']
          # FIXME: https://github.com/Nikkei/node-http-helper/issues/300
          - dependency-name: '@eslint/js'
            update-types: ['version-update:semver-major']
      # - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      groups:
          eslint:
              patterns:
                  - eslint
                  - '@eslint/*'
          typescript-eslint:
              patterns:
                  - '@typescript-eslint/*'

    #####################################################
    #   In-repository composite actions
    #####################################################
    - package-ecosystem: github-actions
      directory: '/.github/actions/prepare_ci'
      schedule:
          interval: monthly
      open-pull-requests-limit: 99
      labels:
          - 'A-dependency/gardening'
          - I-enhancement
