# https://prettier.io/docs/en/configuration.html

semi = true
singleQuote = true
tabWidth = 4
useTabs = false
printWidth = 120

[[overrides]]
files = "turbo.jsonc"
[overrides.options]
# Turborepo 2.5 does not support trailingComma even if in jsonc file.
trailingComma = "none"
