name: Prepare CI
description: This action prepare CI that restore cachable items

runs:
    using: composite
    steps:
        - uses: actions/setup-node@v4
          with:
              node-version: 22
              cache: 'npm'

        # - https://nodejs.org/docs/latest-v19.x/api/corepack.html
        # - https://nodejs.org/docs/latest-v19.x/api/corepack.html
        - name: Enable corepack
          shell: bash
          # See https://github.com/nodejs/corepack/issues/616
          # We install the latest corepack to avoid an installation problem.
          run: |
              npm install -g corepack@latest
              corepack enable

        - name: Install dependencies
          shell: bash
          run: npm ci
