name: Prepare CI
description: This action prepare CI that restore cachable items

runs:
    using: composite
    steps:
        - name: Enable corepack
          shell: bash
          # See https://github.com/nodejs/corepack/issues/616
          # We install the latest corepack to avoid an installation problem.
          run: |
              npm install -g corepack@latest
              corepack enable

        - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
          with:
              node-version: 24
              cache: 'pnpm'

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile --strict-peer-dependencies
