name: Prepare CI
description: This action prepare CI that restore cachable items

runs:
    using: composite
    steps:
        - uses: actions/setup-node@v3
          with:
              node-version: 18
              cache: 'npm'
        - name: Install dependencies
          shell: bash
          run: npm ci
