name: Prepare CI
description: This action prepare CI that restore cachable items

runs:
    using: composite
    steps:
        - name: Enable corepack
          shell: bash
          # See https://github.com/nodejs/corepack/issues/616
          # We install the latest corepack to avoid an installation problem.
          run: |
              npm install -g corepack@latest
              corepack enable

        - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
          with:
              node-version: 24
              cache: 'pnpm'

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile --strict-peer-dependencies
