name: CI on main branch

on:
    push:
        branches:
            - 'main'

# We don't limit this workflow concurrency because there are no order-sensitive workflow.

permissions:
    contents: read

jobs:
    ci:
        uses: ./.github/workflows/_ci.yaml
